### ISSUE TITLE
weird error msg in prepare_dataset.py when unzip not installed

### ISSUE THREAD

**Issue by Timoeller** [brennannicholson/ancient-greek-char-bert#1]
Hey, I am reproducing your results and came a strange error when unzip is not installed:

Traceback (most recent call last):
  File "prepare_dataset.py", line 18, in <module>
    get_data()
  File "/home/ubuntu/ancient-greek-char-bert/data_prep/greek_data_prep/download_data.py", line 22, in get_data
    download(f1kg_address)
  File "/home/ubuntu/ancient-greek-char-bert/data_prep/greek_data_prep/download_data.py", line 14, in download
    subprocess.run(["unzip", filename])
  File "/home/ubuntu/miniconda3/envs/py37/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/ubuntu/miniconda3/envs/py37/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/home/ubuntu/miniconda3/envs/py37/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'unzip': 'unzip'

Maybe you can also install it in one of the previous installation steps?

**Comment by brennannicholson** [comment]
Hey Timoeller, 

Thanks for letting me know about this! I didn't realise that unzip wasn't included in ubuntu by default -- an oversight on my part. I've added check before unzip is called. If it's not found the user is now prompted to install it and try again. You can see the commit here: https://github.com/brennannicholson/ancient-greek-char-bert/commit/b3180dffa9b6574c3d012e8881d128f80779886e
